### ISSUE TITLE
Implementation of findAll 

### ISSUE THREAD

**Issue by maikvortx** [herbsjs/herbs2knex#11]
Hi!

I think findAll should be like findBy, but changing to return all records, correct?

I'm implementing this solution for getAll():

```
async findAll() {

    const tableFields = this.dataMapper.tableFields()    

    const ret = await this.runner
      .select(tableFields);      

    const entities = []

    for (const row of ret) {
      if (row === undefined) continue
      entities.push(this.dataMapper.toEntity(row))
    }

    return entities
  }
```

**Comment by jhomarolo** [comment]
I think this functionality is very good, but I think it is valid to come with the limit option included.

**Comment by maikvortx** [comment]
Hi @jhomarolo !

Something like this:

```
async findAll({ limit: 0 }) {

    const tableFields = this.dataMapper.tableFields()    

    const ret = await this.runner
      .select(tableFields)
      .limit(limit);      

    const entities = []

    for (const row of ret) {
      if (row === undefined) continue
      entities.push(this.dataMapper.toEntity(row))
    }

    return entities
  }
```

**Comment by jhomarolo** [comment]
@maikvortx yes, like this.
Could you please, add this into your PR?

**Comment by dalssoft** [comment]
if you add `offset` as well it would be ready to paginate (offset + limit)

**Comment by maikvortx** [comment]
Hello @dalssoft!
I like the idea of ​​offset. I will implement these solutions and return for validation.

**Comment by dalssoft** [comment]
Cool. For a future PR it would be nice to implement similar options (`{ orderBy, limit, offset }`) on `findBy`

**Comment by maikvortx** [comment]
Ok!

**Comment by maikvortx** [comment]
Hi @jhomarolo !
PR updated with limit paramter.

https://github.com/herbsjs/herbs2knex/pull/13

**Comment by maikvortx** [comment]
@dalssoft, the `findBy` method can be included in` findAll` because the only change is` searchTerm`. What do you think about?

**Comment by maikvortx** [comment]
@dalssoft, i included `find` method and your wrapers` findBy` and `findAll`. You can check? Later i will create another PR with query with pages and other functions.

**Comment by dalssoft** [comment]
Can we close this issue after PR https://github.com/herbsjs/herbs2knex/pull/13?
