### ISSUE TITLE
ID field: use ID metadata from entity

### ISSUE THREAD

**Issue by dalssoft** [herbsjs/herbs2knex#35]
With the upcoming release of the "ID field" feature (https://github.com/herbsjs/gotu/issues/46), it would be possible to read the entity's metadata and, as a convention, use those IDs that today need to be explicitly defined.  

```js
class ItemRepository extends Repository {
    constructor() {
        super({
            entity: Item,
            table: 'aTable',
            ids: ['id'],              // <---- not necessary
            knex: connection
        })
    }
```

Explicitly defining IDs would still be possible, but not mandatory for entities with IDs.

**Comment by euduardo** [comment]
I'm working on this issue.
